import type { NextPage } from 'next';
import Head from 'next/head';
import { Badge, Text } from '@chakra-ui/react';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
      </main>
      <footer>
        <Text fontSize="xl" fontWeight="bold" role="author">
          Saif Bechan
          <Badge ml="1" fontSize="0.8em" colorScheme="green">
            New
          </Badge>
        </Text>
      </footer>
    </div>
  );
};

export default Home;
